name: tg-bot

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        CONSUMER_API_KEY: ${{ secrets.CONSUMER_API_KEY }}
        CONSUMER_API_SECRET_KEY: ${{ secrets.CONSUMER_API_SECRET_KEY }}
        ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
        ACCESS_SECRET_KEY: ${{ secrets.ACCESS_SECRET_KEY }}
      run: cargo run
